# services: 
#   pg: 
#     image: bitnami/postgresql:latest
#     ports: 
#       - "5432:5432"
#     environment: 
#       - POSTGRES_USER=docker
#       - POSTGRES_PASSWORD=docker
#       - POSTGRES_DB=upload
#     volumes:
#       - "./docker:/docker-entrypoint-initdb.d"


services: 
  pg:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=brevly
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - db
      - widget
volumes:
  pg:
networks:
  db:
    driver: bridge
  widget: 
    driver: bridge